#!/usr/bin/env python3
"""Generate markdown bridge index for non-markdown files."""

from __future__ import annotations

import argparse
import pathlib
from collections import defaultdict


SKIP_PARTS = {".git", ".claude", "node_modules", "agent-transcripts", "__pycache__", ".venv", "venv"}
SKIP_SUFFIXES = {".md"}


def list_non_md_files(root: pathlib.Path) -> list[pathlib.Path]:
    from _graph_paths import should_skip_file

    files: list[pathlib.Path] = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if should_skip_file(path, root):
            continue
        if path.suffix.lower() in SKIP_SUFFIXES:
            continue
        files.append(path)
    return files


def cluster_name(rel: pathlib.PurePosixPath) -> str:
    if len(rel.parts) >= 2:
        return "/".join(rel.parts[:2])
    return rel.parts[0]


def build_index_content(root: pathlib.Path, files: list[pathlib.Path]) -> str:
    grouped: dict[str, list[str]] = defaultdict(list)
    for path in sorted(files):
        rel = path.relative_to(root).as_posix()
        grouped[cluster_name(pathlib.PurePosixPath(rel))].append(rel)

    lines: list[str] = [
        "# Non-Markdown Bridge Notes",
        "",
        "Auto-generated bridge index for non-markdown files.",
        "For **Python and XML** graph edges (wikilinks), use [[code_graph_hub]] and `30_system/docs/bridges/clusters/cluster_*.md`.",
        "",
        "## Hub Links",
        "",
        "- [[README]]",
        "- [[code_graph_hub]]",
        "- [[30_system/docs/GRAPH_CONNECTIVITY_MAP]]",
        "- [[30_system/docs/AUTOMATION_INDEX]]",
        "- [[30_system/docs/ALL_NOTES_INDEX]]",
        "- [[40_operations/scripts/README]]",
        "",
        "## Coverage",
        "",
        f"- Total non-markdown files indexed (backtick list): {len(files)}",
        f"- Total clusters: {len(grouped)}",
        f"- Python/XML wikilink bridges: run `generate_code_bridge_clusters.py`",
        "",
    ]

    for cluster in sorted(grouped):
        lines.append(f"## Cluster `{cluster}`")
        lines.append("")
        for rel in grouped[cluster]:
            lines.append(f"- `{rel}`")
        lines.append("")

    lines.extend(
        [
            "## Notes",
            "",
            "- This file is generated by `40_operations/scripts/generate_non_md_index.py`.",
            "- For validation, run `40_operations/scripts/validate_non_md_index.py`.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate non-markdown bridge index.")
    parser.add_argument("--root", default=".", help="Workspace root (default: current directory).")
    parser.add_argument(
        "--output",
        default="30_system/docs/bridges/non_markdown_bridges.md",
        help="Output markdown path relative to root.",
    )
    args = parser.parse_args()

    root = pathlib.Path(args.root).resolve()
    output = root / args.output
    output.parent.mkdir(parents=True, exist_ok=True)

    files = list_non_md_files(root)
    content = build_index_content(root, files)
    output.write_text(content, encoding="utf-8")

    print(f"Generated: {output.relative_to(root).as_posix()}")
    print(f"Indexed non-markdown files: {len(files)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
