# -*- coding: utf-8 -*-
"""Proširi wines.json: split kompozita + flagship dodaci (pairing-first).

Pokretanje (iz app/):
  python scripts/expand-wines.py
  python scripts/expand-wines.py --dry-run
"""
from __future__ import annotations

import argparse
import json
from copy import deepcopy
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WINES_PATH = ROOT / "src" / "data" / "wines.json"

CLEAN = {
    "hr": "Standardno vinarstvo (sulfiti)",
    "en": "Standard winemaking (sulphites)",
}
FORTIFIED = {
    "hr": "Fortificirano vinskim destilatom; slatkoca iz zaustavljene fermentacije",
    "en": "Fortified with grape spirit; sweetness from arrested fermentation",
}
SPARKLING_BRUT = {
    "hr": "Standardno vinarstvo (sulfiti); dozaza secera u brut razini (<12 g/L)",
    "en": "Standard winemaking (sulphites); sugar dosage at brut level (<12 g/L)",
}
DESSERT = {
    "hr": "Standardno vinarstvo (sulfiti); prirodni zaostali secer (botritis / kasna berba)",
    "en": "Standard winemaking (sulphites); natural residual sugar (botrytis / late harvest)",
}

REMOVE_IDS = {
    "wine-vintage-port", "wine-blandys-madeira-10", "wine-prosek-hvar", "wine-dingac",
    "wine-plavac-mali", "wine-postup", "wine-babic", "wine-amarone", "wine-ripasso",
    "wine-barolo", "wine-brunello", "wine-rioja-gran-reserva", "wine-crljenak",
    "wine-cabernet-sauvignon", "wine-malbec-mendoza", "wine-syrah-shiraz", "wine-zinfandel",
    "wine-chateauneuf", "wine-chianti-classico", "wine-pinot-noir", "wine-merlot-istra",
    "wine-frankovka", "wine-grasevina", "wine-posip", "wine-malvazija",
    "wine-chardonnay-barrique", "wine-riesling-mosel", "wine-champagne-brut",
    "wine-prosecco-docg", "wine-cartizze", "wine-cava-juve-y-camps", "wine-tomac-pjenusac",
    "wine-misal-persuric", "wine-sauternes",
}

KEEP_IDS = {
    "wine-grahams-tawny-10", "wine-grahams-tawny-20", "wine-sandeman-tawny-20",
    "wine-taylors-lbv", "wine-fonseca-bin-27", "wine-grahams-six-grapes",
    "wine-lustau-amontillado", "wine-lustau-oloroso", "wine-lustau-px",
    "wine-tio-pepe-fino", "wine-teran", "wine-primitivo-sessantanni",
    "wine-franciacorta-ca-del-bosco", "wine-muskat-momjanski",
    "wine-mionetto-prosecco-doc", "wine-nino-franco-rustico", "wine-bottega-gold",
    "wine-tokaji-aszu-5", "wine-tokaji-aszu-6", "wine-tokaji-aszu-3",
    "wine-tokaji-essencia", "wine-tokaji-szamorodni-edes", "wine-tokaji-furmint-dry",
}

RENAMES = {
    "wine-tio-pepe-fino": "Tio Pepe Fino (Gonzalez Byass)",
    "wine-tokaji-aszu-5": "Royal Tokaji Aszú 5 Puttonyos",
    "wine-tokaji-aszu-6": "Oremus Tokaji Aszú 6 Puttonyos",
    "wine-tokaji-aszu-3": "Disznókő Tokaji Aszú 3 Puttonyos",
    "wine-tokaji-essencia": "Royal Tokaji Essencia",
    "wine-tokaji-szamorodni-edes": "Oremus Tokaji Szamorodni Édes",
    "wine-tokaji-furmint-dry": "Disznókő Tokaji Furmint (suhi)",
    "wine-teran": "Coronica Gran Teran",
}


def W(
    id, name, style, region, abv, body, sweetness, tags, qs, price, shop, serve,
    notes_hr, notes_en, *, additive="clean", detail=None, source="Standard kategorije vino",
    price_url=None, approx=True,
):
    if detail is None:
        if additive == "fortified":
            detail = FORTIFIED
            source = "Standard kategorije porto/sherry/madeira"
        elif style == "sparkling":
            detail = SPARKLING_BRUT
            source = "Standard kategorije pjenusac"
        elif style in ("dessert-wine", "prosek") and sweetness >= 4:
            detail = DESSERT
        else:
            detail = CLEAN
    out = {
        "id": id, "category": "wine", "name": name, "style": style, "region": region,
        "abv": abv, "body": body, "sweetness": sweetness, "flavorTags": tags,
        "additiveStatus": additive, "additiveDetail": detail, "additiveSource": source,
        "qualityScore": qs, "priceEUR": {"min": price[0], "max": price[1]},
        "shopHR": shop, "status": None, "pairable": True,
        "serving": {"best": serve}, "cigarHint": None, "priceUrl": price_url,
        "notes": {"hr": notes_hr, "en": notes_en},
    }
    if approx:
        out["priceApprox"] = True
    return out


def new_entries():
    v, viv, hr = "Vinoteke", "Vivat fina vina / vinoteke", "Konzum / vinoteke"
    F = "fortified"
    return [
        W("wine-taylors-vintage", "Taylor's Vintage Port", "port-ruby", "Douro, Portugal", 20, 5, 4,
          ["tamno-voce", "kakao", "zacini", "hrast"], 9.0, (90, 160), viv, "Casa za porto, 14-16 C",
          "Deklarirano godiste Taylor's: crna tresnja, kakao, zacini, dug zivot. Vrh piramide uz punu cigaru.",
          "Declared Taylor's vintage: black cherry, cocoa, spice, long life. Peak of the pyramid with a full cigar.",
          additive=F),
        W("wine-grahams-vintage", "Graham's Vintage Port", "port-ruby", "Douro, Portugal", 20, 5, 4,
          ["tamno-voce", "kakao", "suho-voce", "zacini"], 9.0, (90, 160), viv, "Casa za porto, 14-16 C",
          "Graham's vintage: bogato tamno voce i cokolada, malo sladi stil od Taylor's. Klasican pairing uz maduro.",
          "Graham's vintage: rich dark fruit and chocolate, a touch sweeter than Taylor's. Classic pairing with maduro.",
          additive=F),
        W("wine-dows-vintage", "Dow's Vintage Port", "port-ruby", "Douro, Portugal", 20, 5, 4,
          ["tamno-voce", "zacini", "kakao", "hrast"], 9.0, (85, 150), viv, "Casa za porto, 14-16 C",
          "Dow's: susi, strukturiraniji vintage; crno voce i papar. Odlican uz Habano punoce.",
          "Dow's: drier, more structured vintage; black fruit and pepper. Excellent with full Habano.",
          additive=F),
        W("wine-taylors-tawny-10", "Taylor's Tawny Port 10 Y.O.", "port-tawny", "Douro, Portugal", 20, 3, 4,
          ["orasasti", "karamela", "suho-voce"], 8.0, (32, 42), viv, "Casa za porto, 14-16 C",
          "Taylor's 10 YO tawny: orasi, karamela, suhe smokve. Pouzdan partner srednjoj cigari.",
          "Taylor's 10 YO tawny: nuts, caramel, dried figs. A reliable partner for a medium cigar.",
          additive=F),
        W("wine-taylors-tawny-20", "Taylor's Tawny Port 20 Y.O.", "port-tawny", "Douro, Portugal", 20, 4, 4,
          ["orasasti", "karamela", "suho-voce", "hrast"], 8.5, (55, 75), viv, "Casa za porto, 14-16 C",
          "Dublji Taylor's 20 YO: peceni orasi, datulje, fina oksidacija. Univerzalan uz maduro.",
          "Deeper Taylor's 20 YO: roasted nuts, dates, fine oxidation. Universal with maduro.",
          additive=F),
        W("wine-dows-lbv", "Dow's Late Bottled Vintage", "port-ruby", "Douro, Portugal", 20, 4, 4,
          ["tamno-voce", "zacini", "kakao"], 7.5, (18, 28), viv, "Casa za porto, 14-16 C",
          "Dow's LBV: zrelo crno voce i zacini bez vintage cijene. Dobar svakodnevni ruby uz cigaru.",
          "Dow's LBV: ripe black fruit and spice without vintage pricing. A solid everyday ruby with a cigar.",
          additive=F),
        W("wine-warres-otima-10", "Warre's Otima 10 Y.O. Tawny", "port-tawny", "Douro, Portugal", 20, 3, 4,
          ["orasasti", "karamela", "med"], 7.5, (25, 35), v, "Casa za porto, 14-16 C",
          "Warre's Otima: mekani tawny; orasi i med. Lagan ulaz u porto uz cigaru.",
          "Warre's Otima: soft tawny; nuts and honey. An easy entry to port with a cigar.",
          additive=F),
        W("wine-fonseca-tawny-20", "Fonseca 20 Y.O. Tawny Port", "port-tawny", "Douro, Portugal", 20, 4, 4,
          ["orasasti", "karamela", "suho-voce", "med"], 8.5, (55, 75), viv, "Casa za porto, 14-16 C",
          "Fonseca 20 YO: bogat tawny; orasi, karamela, suhe smokve. Rival Graham's uz maduro.",
          "Fonseca 20 YO: rich tawny; nuts, caramel, dried figs. A rival to Graham's with maduro.",
          additive=F),
        W("wine-grahams-lbv", "Graham's Late Bottled Vintage", "port-ruby", "Douro, Portugal", 20, 4, 4,
          ["tamno-voce", "kakao", "zacini"], 7.5, (18, 28), viv, "Casa za porto, 14-16 C",
          "Graham's LBV: vocniji, sladi LBV stil. Laksi ulaz u ruby porto uz cigaru.",
          "Graham's LBV: fruitier, sweeter LBV style. An easier entry to ruby port with a cigar.",
          additive=F),
        W("wine-niepoort-ruby", "Niepoort Ruby Dum", "port-ruby", "Douro, Portugal", 19.5, 4, 4,
          ["tamno-voce", "voce", "zacini"], 7.5, (14, 22), v, "Casa za porto, 14-16 C",
          "Niepoort Ruby Dum: moderniji, vocni ruby. Svjeziji porto profil uz srednju cigaru.",
          "Niepoort Ruby Dum: a more modern, fruity ruby. Fresher port profile with a medium cigar.",
          additive=F),
        W("wine-la-gitana-manzanilla", "Hidalgo La Gitana Manzanilla", "sherry-dry", "Sanlucar, Spanjolska", 15, 2, 1,
          ["mineralno", "orasasti", "citrus"], 8.0, (12, 18), viv, "Dobro ohladjeno, 6-8 C",
          "Najpoznatija manzanilla: morska svjezina, badem, limuna kora. Uz najblazu Connecticut cigaru.",
          "The best-known manzanilla: sea breeze, almond, lemon peel. With the mildest Connecticut.",
          additive=F, source="Standard kategorije sherry"),
        W("wine-valdespino-tio-diego", "Valdespino Tio Diego Amontillado", "sherry-dry", "Jerez, Spanjolska", 18, 3, 1,
          ["orasasti", "suho-voce", "mineralno"], 8.5, (22, 32), v, "Casa za sherry, 12-14 C",
          "Valdespino amontillado: orasi, jod, suha jabuka. Most izmedu fino i olorosa uz srednju cigaru.",
          "Valdespino amontillado: nuts, iodine, dried apple. Bridge from fino to oloroso with a medium cigar.",
          additive=F, source="Standard kategorije sherry"),
        W("wine-lustau-east-india", "Lustau East India Solera", "sherry-sweet", "Jerez, Spanjolska", 20, 4, 4,
          ["orasasti", "suho-voce", "karamela", "med"], 8.0, (18, 28), viv, "Casa za sherry, 14-16 C",
          "East India Solera: cream/oloroso stil; orasi i suho voce. Odlican uz Connecticut do maduro.",
          "East India Solera: cream/oloroso style; nuts and dried fruit. Excellent from Connecticut to maduro.",
          additive=F, source="Standard kategorije sherry"),
        W("wine-blandys-bual-10", "Blandy's Bual 10 Y.O.", "madeira", "Madeira, Portugal", 19, 4, 4,
          ["orasasti", "suho-voce", "karamela", "med"], 8.0, (35, 48), viv, "Casa za madeira, 14-16 C",
          "Bual 10 YO: karamela, suhe marelice, dimna nota. Odlican uz maduro srednje snage.",
          "Bual 10 YO: caramel, dried apricot, a smoky note. Excellent with a medium-strength maduro.",
          additive=F, source="Standard kategorije madeira"),
        W("wine-blandys-malmsey-10", "Blandy's Malmsey 10 Y.O.", "madeira", "Madeira, Portugal", 19, 4, 5,
          ["med", "suho-voce", "karamela", "orasasti"], 8.0, (35, 48), viv, "Casa za madeira, 14-16 C",
          "Malmsey 10 YO: najsladi stil madeire; med, smokve, orasi. Desert uz blagi do srednji maduro.",
          "Malmsey 10 YO: Madeira's sweetest style; honey, figs, nuts. Dessert with a mild-to-medium maduro.",
          additive=F, source="Standard kategorije madeira"),
        W("wine-hh-madeira-10", "Henriques & Henriques 10 Y.O. Medium Rich", "madeira", "Madeira, Portugal", 19, 4, 4,
          ["orasasti", "karamela", "suho-voce"], 7.5, (28, 40), v, "Casa za madeira, 14-16 C",
          "H&H medium rich: uravnotezen madeira profil; orasi i karamela. Dobra alternativa Blandy's.",
          "H&H medium rich: balanced Madeira profile; nuts and caramel. A solid alternative to Blandy's.",
          additive=F, source="Standard kategorije madeira"),
        W("wine-tomic-prosek", "Tomic Prosek", "prosek", "Hvar, Hrvatska", 16, 4, 5,
          ["suho-voce", "med", "orasasti"], 8.0, (25, 40), hr, "Mala casa, 12-14 C",
          "Tomic s Hvara: tradicionalni prosek od plavca; suhe smokve i med. Lokalni desert uz cigaru.",
          "Tomic from Hvar: traditional Plavac prosek; dried figs and honey. A local dessert with a cigar.",
          additive=F, source="Standard kategorije prosek"),
        W("wine-plancic-prosek", "Plancic Prosek", "prosek", "Hvar, Hrvatska", 15.5, 4, 5,
          ["med", "suho-voce", "karamela"], 7.5, (22, 35), hr, "Mala casa, 12-14 C",
          "Plancic: bogat hvarski prosek; med i suho voce. HR alternativa uz blagi maduro.",
          "Plancic: rich Hvar prosek; honey and dried fruit. A Croatian alternative with a mild maduro.",
          additive=F, source="Standard kategorije prosek"),
        W("wine-rieussec-sauternes", "Chateau Rieussec Sauternes", "dessert-wine", "Bordeaux, Francuska", 13.5, 4, 5,
          ["med", "suho-voce", "citrus", "karamela"], 8.5, (45, 80), viv, "Ohladjeno, 8-10 C",
          "Rieussec: botritis med, marelica, limun. Klasika uz blagi maduro ili desert.",
          "Rieussec: botrytis honey, apricot, lemon. Classic with a mild maduro or dessert."),
        W("wine-suduiraut-sauternes", "Chateau Suduiraut Sauternes", "dessert-wine", "Bordeaux, Francuska", 13.5, 4, 5,
          ["med", "suho-voce", "karamela", "citrus"], 8.5, (50, 90), v, "Ohladjeno, 8-10 C",
          "Suduiraut: gust, kremast Sauternes; ananas, med, vanilija. Ozbiljan desertni pairing.",
          "Suduiraut: dense, creamy Sauternes; pineapple, honey, vanilla. A serious dessert pairing."),
        W("wine-disznoko-aszu-5", "Disznoko Tokaji Aszu 5 Puttonyos", "dessert-wine", "Tokaj, Madarska", 11.5, 4, 5,
          ["med", "suho-voce", "citrus", "karamela"], 8.5, (40, 65), viv, "Ohladjeno, 8-10 C",
          "Disznoko 5 putt: med, marelica, limunova kora. Pouzdan Tokaj uz cigaru.",
          "Disznoko 5 putt: honey, apricot, lemon zest. Reliable Tokaji with a cigar."),
        # HR crveno
        W("wine-skaramuca-dingac", "Skaramuca Dingac", "red-full", "Peljesac, Hrvatska", 14.5, 5, 2,
          ["tamno-voce", "suho-voce", "zacini", "zemljano"], 8.5, (28, 45), "Madirazza / vinoteke", "Velika casa, 16-18 C",
          "Skaramuca s polozaja Dingac: zreli plavac, suha tresnja, zacini. Vrh HR crvenog uz Habano.",
          "Skaramuca from the Dingac site: ripe Plavac, dried cherry, spice. Peak Croatian red with Habano."),
        W("wine-madirazza-dingac", "Madirazza Dingac", "red-full", "Peljesac, Hrvatska", 14.5, 5, 2,
          ["tamno-voce", "zacini", "suho-voce", "hrast"], 8.5, (29, 52), "Madirazza webshop / vinoteke", "Velika casa, 16-18 C",
          "Madirazza Dingac: koncentrirani plavac s juzne padine. Klasican HR pairing uz punu cigaru.",
          "Madirazza Dingac: concentrated Plavac from the southern slope. Classic HR pairing with a full cigar."),
        W("wine-saints-hills-dingac", "Saints Hills Dingac", "red-full", "Peljesac, Hrvatska", 14.5, 5, 2,
          ["tamno-voce", "zacini", "hrast", "suho-voce"], 8.5, (35, 55), viv, "Velika casa, 16-18 C",
          "Saints Hills: moderniji, bacveni Dingac; crno voce i vanilija. Snaga uz maduro.",
          "Saints Hills: a more modern, barrel-aged Dingac; black fruit and vanilla. Power with maduro."),
        W("wine-zlatan-plavac", "Zlatan Otok Plavac Mali", "red-full", "Hvar, Hrvatska", 14, 4, 2,
          ["tamno-voce", "zacini", "zemljano"], 7.5, (12, 22), hr, "Velika casa, 16-18 C",
          "Zlatan: tipican hvarski plavac; tresnja, papar, mediteran. Solidan HR crveni uz srednju cigaru.",
          "Zlatan: typical Hvar Plavac; cherry, pepper, Mediterranean notes. Solid HR red with a medium cigar."),
        W("wine-korta-katarina-plavac", "Korta Katarina Plavac Mali", "red-full", "Peljesac, Hrvatska", 14.5, 4, 2,
          ["tamno-voce", "hrast", "zacini"], 8.0, (25, 40), viv, "Velika casa, 16-18 C",
          "Korta Katarina: ureden, medunarodni stil plavca. Dobar most prema Novom svijetu uz cigaru.",
          "Korta Katarina: polished, international Plavac style. A good bridge to New World with a cigar."),
        W("wine-matusko-postup", "Matusko Postup", "red-full", "Peljesac, Hrvatska", 14.5, 5, 2,
          ["tamno-voce", "suho-voce", "zacini"], 8.0, (25, 42), hr, "Velika casa, 16-18 C",
          "Matusko Postup: susjed Dingaca; zrelo voce i struktura. Ozbiljan plavac uz Habano.",
          "Matusko Postup: Dingac's neighbour; ripe fruit and structure. Serious Plavac with Habano."),
        W("wine-madirazza-postup", "Madirazza Postup", "red-full", "Peljesac, Hrvatska", 14.5, 5, 2,
          ["tamno-voce", "zacini", "zemljano"], 8.0, (24, 40), "Madirazza webshop", "Velika casa, 16-18 C",
          "Madirazza Postup: tamno voce i mediteranski zacini. Pairing blizak Dingacu.",
          "Madirazza Postup: dark fruit and Mediterranean spice. Pairing close to Dingac."),
        W("wine-testament-babic", "Testament Babic", "red-full", "Primosten, Hrvatska", 14, 4, 2,
          ["tamno-voce", "mineralno", "zacini"], 8.0, (18, 30), viv, "Velika casa, 16-18 C",
          "Testament: moderno primostensko babic; mineralnost i crvena tresnja. Karakter uz srednje-punu cigaru.",
          "Testament: modern Primosten Babic; minerality and red cherry. Character with a medium-full cigar."),
        W("wine-grabovac-babic", "Grabovac Babic", "red-full", "Primosten, Hrvatska", 13.5, 4, 1,
          ["tamno-voce", "zemljano", "zacini"], 7.5, (14, 24), hr, "Velika casa, 16-18 C",
          "Grabovac: klasicni babic s kamenjara. Zemljano i zacinsko uz Habano srednje snage.",
          "Grabovac: classic Babic from rocky soils. Earthy and spicy with a medium Habano."),
        W("wine-zlatan-crljenak", "Zlatan Otok Crljenak", "red-full", "Hvar, Hrvatska", 14, 4, 2,
          ["tamno-voce", "zacini", "voce"], 7.5, (18, 32), hr, "Velika casa, 16-18 C",
          "Crljenak (zinfandelov predak): crveno voce i papar. Zanimljiv HR most prema CA zinu.",
          "Crljenak (Zinfandel ancestor): red fruit and pepper. An interesting HR bridge to CA Zin."),
        W("wine-rizman-tribidrag", "Rizman Tribidrag", "red-full", "Dalmacija, Hrvatska", 14, 4, 2,
          ["tamno-voce", "zacini", "hrast"], 7.5, (20, 35), viv, "Velika casa, 16-18 C",
          "Rizman Tribidrag: isto sortno ime, bacveniji stil. Punije tijelo uz maduro.",
          "Rizman Tribidrag: same variety, more barrel-led style. Fuller body with maduro."),
        W("wine-plenkovic-zlatan", "Zlatan Plenkovic Grand Cru Plavac", "red-full", "Hvar, Hrvatska", 14.5, 5, 2,
          ["tamno-voce", "suho-voce", "zacini", "hrast"], 8.0, (30, 50), viv, "Velika casa, 16-18 C",
          "Zlatan Grand Cru: vrhunski hvarski plavac; koncentracija i zacini. Uz Habano/maduro.",
          "Zlatan Grand Cru: top Hvar Plavac; concentration and spice. With Habano/maduro."),
        # IT / ES / FR
        W("wine-masi-costasera", "Masi Costasera Amarone", "red-full", "Veneto, Italija", 15, 5, 2,
          ["suho-voce", "tamno-voce", "kakao", "zacini"], 8.5, (40, 60), viv, "Velika casa, 16-18 C",
          "Masi Costasera: suha tresnja, cokolada, zacini. Jedan od najpouzdanijih Amaronea uz cigaru.",
          "Masi Costasera: dried cherry, chocolate, spice. One of the most reliable Amarones with a cigar."),
        W("wine-allegrini-amarone", "Allegrini Amarone della Valpolicella", "red-full", "Veneto, Italija", 15.5, 5, 2,
          ["suho-voce", "tamno-voce", "kakao", "hrast"], 8.5, (55, 80), viv, "Velika casa, 16-18 C",
          "Allegrini: elegantniji, koncentrirani Amarone. Suho voce i kakao uz punu cigaru.",
          "Allegrini: a more elegant, concentrated Amarone. Dried fruit and cocoa with a full cigar."),
        W("wine-masi-campofiorin", "Masi Campofiorin", "red-medium", "Veneto, Italija", 13.5, 3, 2,
          ["tamno-voce", "zacini", "voce"], 7.5, (12, 20), viv, "Casa, 15-17 C",
          "Campofiorin: ripasso-stil Masi; tresnja i zacini. Laksi ulaz u Valpolicellu uz blagu cigaru.",
          "Campofiorin: Masi's ripasso style; cherry and spice. An easier Valpolicella entry with a mild cigar."),
        W("wine-cesari-ripasso", "Cesari Mara Valpolicella Ripasso", "red-medium", "Veneto, Italija", 13.5, 3, 2,
          ["tamno-voce", "suho-voce", "zacini"], 7.5, (14, 22), v, "Casa, 15-17 C",
          "Cesari Mara: popularni ripasso; suha tresnja i blaga slatkoca. Svakodnevni pairing.",
          "Cesari Mara: popular ripasso; dried cherry and gentle sweetness. An everyday pairing."),
        W("wine-masi-brolo", "Masi Brolo di Campofiorin", "red-full", "Veneto, Italija", 14, 4, 2,
          ["suho-voce", "tamno-voce", "zacini"], 8.0, (22, 35), viv, "Velika casa, 16-18 C",
          "Brolo: premium Campofiorin linija; suha tresnja i zacini. Most prema Amaroneu.",
          "Brolo: premium Campofiorin line; dried cherry and spice. A bridge toward Amarone."),
        W("wine-fontanafredda-barolo", "Fontanafredda Barolo", "red-full", "Piemont, Italija", 14, 4, 1,
          ["cvjetno", "tamno-voce", "koza", "zemljano"], 8.5, (35, 55), viv, "Velika casa, 16-18 C",
          "Fontanafredda: klasicni Barolo; ruza, katran, visnja. Tannini uz strukturiranu cigaru.",
          "Fontanafredda: classic Barolo; rose, tar, cherry. Tannins with a structured cigar."),
        W("wine-pio-cesare-barolo", "Pio Cesare Barolo", "red-full", "Piemont, Italija", 14, 4, 1,
          ["cvjetno", "tamno-voce", "koza", "hrast"], 8.5, (45, 70), viv, "Velika casa, 16-18 C",
          "Pio Cesare: tradicionalni, snazni Barolo. Koza i crveno voce uz Habano.",
          "Pio Cesare: traditional, powerful Barolo. Leather and red fruit with Habano."),
        W("wine-banfi-brunello", "Castello Banfi Brunello di Montalcino", "red-full", "Toskana, Italija", 14, 4, 1,
          ["tamno-voce", "koza", "zemljano", "hrast"], 8.0, (40, 65), viv, "Velika casa, 16-18 C",
          "Banfi Brunello: siroko dostupan, zreo sangiovese. Visnja i hrast uz srednje-punu cigaru.",
          "Banfi Brunello: widely available, ripe Sangiovese. Cherry and oak with a medium-full cigar."),
        W("wine-casanova-di-neri-brunello", "Casanova di Neri Brunello di Montalcino", "red-full", "Toskana, Italija", 14.5, 4, 1,
          ["tamno-voce", "hrast", "koza", "zacini"], 8.5, (55, 90), v, "Velika casa, 16-18 C",
          "Casanova di Neri: moderniji, koncentrirani Brunello. Snaga i elegancija uz maduro.",
          "Casanova di Neri: a more modern, concentrated Brunello. Power and elegance with maduro."),
        W("wine-faustino-i-gr", "Faustino I Gran Reserva", "red-full", "Rioja, Spanjolska", 13.5, 4, 1,
          ["orasasti", "suho-voce", "vanilija", "tamno-voce"], 8.0, (22, 35), viv, "Velika casa, 16-18 C",
          "Faustino I GR: klasik Rioje; vanilija, suha tresnja, orasi. Prijateljski uz Connecticut do Habano.",
          "Faustino I GR: Rioja classic; vanilla, dried cherry, nuts. Friendly from Connecticut to Habano."),
        W("wine-muga-gran-reserva", "Muga Gran Reserva", "red-full", "Rioja, Spanjolska", 14, 4, 1,
          ["tamno-voce", "hrast", "orasasti", "zacini"], 8.5, (40, 60), viv, "Velika casa, 16-18 C",
          "Muga GR: ozbiljnija Rioja; hrast, crno voce, zacini. Bolje uz puniju cigaru.",
          "Muga GR: a more serious Rioja; oak, black fruit, spice. Better with a fuller cigar."),
        W("wine-pesquera-ribera", "Tinto Pesquera Crianza", "red-full", "Ribera del Duero, Spanjolska", 14, 4, 1,
          ["tamno-voce", "hrast", "zacini"], 8.0, (25, 40), viv, "Velika casa, 16-18 C",
          "Pesquera: Tempranillo s Ribere; crna tresnja i hrast. Pouzdan uz Habano.",
          "Pesquera: Ribera Tempranillo; black cherry and oak. Reliable with Habano."),
        W("wine-alvaro-palacios-terrasses", "Alvaro Palacios Les Terrasses", "red-full", "Priorat, Spanjolska", 14.5, 5, 1,
          ["tamno-voce", "mineralno", "zacini", "hrast"], 8.5, (30, 45), v, "Velika casa, 16-18 C",
          "Les Terrasses: pristupacni Priorat; skriljevac, crno voce, alkoholna snaga. Uz maduro.",
          "Les Terrasses: approachable Priorat; slate, black fruit, alcoholic power. With maduro."),
        W("wine-emilio-moro", "Emilio Moro Ribera del Duero", "red-full", "Ribera del Duero, Spanjolska", 14.5, 4, 1,
          ["tamno-voce", "hrast", "zacini"], 8.0, (22, 35), viv, "Velika casa, 16-18 C",
          "Emilio Moro: zreo Ribera stil; voce i bacva. Svakodnevni spanjolski pairing.",
          "Emilio Moro: ripe Ribera style; fruit and barrel. An everyday Spanish pairing."),
        W("wine-capcanes-priorat", "Celler de Capcanes Mas Donis Priorat", "red-full", "Priorat, Spanjolska", 14.5, 4, 1,
          ["tamno-voce", "mineralno", "zacini"], 7.5, (14, 22), viv, "Velika casa, 16-18 C",
          "Mas Donis: pristupacni Priorat; skriljevac i crno voce. Value uz Habano.",
          "Mas Donis: approachable Priorat; slate and black fruit. Value with Habano."),
        W("wine-beaucastel-cdp", "Chateau de Beaucastel Chateauneuf-du-Pape", "red-full", "Rhone, Francuska", 14.5, 4, 1,
          ["tamno-voce", "zacini", "zemljano", "koza"], 8.5, (55, 90), viv, "Velika casa, 16-18 C",
          "Beaucastel: garrigue, crno voce, 13 sorti. Referentni CdP uz Habano.",
          "Beaucastel: garrigue, black fruit, 13 varieties. Benchmark CdP with Habano."),
        W("wine-vieux-telegraphe-cdp", "Vieux Telegraphe Chateauneuf-du-Pape", "red-full", "Rhone, Francuska", 14.5, 4, 1,
          ["tamno-voce", "zacini", "zemljano", "mineralno"], 8.5, (50, 85), v, "Velika casa, 16-18 C",
          "Vieux Telegraphe: kamenito, zacinsko CdP s La Crau. Elegancija uz punu cigaru.",
          "Vieux Telegraphe: stony, spicy CdP from La Crau. Elegance with a full cigar."),
        W("wine-guigal-cotes-du-rhone", "E. Guigal Cotes du Rhone", "red-full", "Rhone, Francuska", 14, 3, 1,
          ["tamno-voce", "zacini", "papar"], 7.5, (10, 16), hr, "Casa, 15-17 C",
          "Guigal CdR: Syrah/Grenache pristupacnost; papar i crveno voce. Ulaz u Rhone uz cigaru.",
          "Guigal CdR: approachable Syrah/Grenache; pepper and red fruit. A Rhone entry with a cigar."),
        W("wine-guigal-gigondas", "E. Guigal Gigondas", "red-full", "Rhone, Francuska", 14.5, 4, 1,
          ["tamno-voce", "zacini", "zemljano"], 8.0, (20, 32), viv, "Velika casa, 16-18 C",
          "Guigal Gigondas: puniji juzni Rhone; garrigue i crno voce. Blizu CdP-a uz manju cijenu.",
          "Guigal Gigondas: fuller southern Rhone; garrigue and black fruit. Near CdP at a lower price."),
        W("wine-gaja-barbaresco", "Gaja Barbaresco", "red-full", "Piemont, Italija", 14, 4, 1,
          ["cvjetno", "tamno-voce", "koza", "mineralno"], 9.0, (120, 220), v, "Velika casa, 16-18 C",
          "Gaja Barbaresco: ikona Piemonta; elegancija i snaga. Posebna prilika uz fine Habano.",
          "Gaja Barbaresco: a Piedmont icon; elegance and power. A special occasion with fine Habano."),
        W("wine-ornellaia", "Ornellaia Bolgheri Superiore", "red-full", "Toskana, Italija", 14.5, 5, 1,
          ["tamno-voce", "hrast", "zacini", "kakao"], 9.0, (150, 250), v, "Velika casa, 16-18 C",
          "Ornellaia: Bordeaux blend s toskanske obale. Koncentracija uz vrhunski maduro.",
          "Ornellaia: Bordeaux blend from the Tuscan coast. Concentration with a top maduro."),
        W("wine-antinori-tignanello", "Antinori Tignanello", "red-full", "Toskana, Italija", 14, 4, 1,
          ["tamno-voce", "hrast", "zacini", "koza"], 8.5, (80, 130), v, "Velika casa, 16-18 C",
          "Tignanello: ikona Super Toscane; Sangiovese + Cabernet. Elegancija uz punu cigaru.",
          "Tignanello: Super Tuscan icon; Sangiovese plus Cabernet. Elegance with a full cigar."),
        # Novi svijet
        W("wine-catena-malbec", "Catena Malbec", "red-full", "Mendoza, Argentina", 14, 4, 2,
          ["tamno-voce", "zacini", "vanilija"], 7.5, (12, 20), hr, "Velika casa, 16-18 C",
          "Catena: referentni Mendoza Malbec; sljiva i zacini. Prijateljski uz srednju cigaru.",
          "Catena: benchmark Mendoza Malbec; plum and spice. Friendly with a medium cigar."),
        W("wine-norton-reserva-malbec", "Norton Reserva Malbec", "red-full", "Mendoza, Argentina", 14, 4, 2,
          ["tamno-voce", "hrast", "vanilija"], 7.5, (10, 18), hr, "Velika casa, 16-18 C",
          "Norton Reserva: bacveniji Malbec; vanilija i crno voce. Value pairing.",
          "Norton Reserva: more barrel-led Malbec; vanilla and black fruit. Value pairing."),
        W("wine-penfolds-bin-28", "Penfolds Bin 28 Kalimna Shiraz", "red-full", "Barossa, Australija", 14.5, 5, 2,
          ["tamno-voce", "zacini", "hrast", "kakao"], 8.0, (25, 40), viv, "Velika casa, 16-18 C",
          "Bin 28: klasicni Barossa Shiraz; dzem, papar, hrast. Snaga uz maduro.",
          "Bin 28: classic Barossa Shiraz; jam, pepper, oak. Power with maduro."),
        W("wine-penfolds-bin-389", "Penfolds Bin 389 Cabernet Shiraz", "red-full", "Juzna Australija", 14.5, 5, 1,
          ["tamno-voce", "hrast", "zacini", "kakao"], 8.5, (45, 70), viv, "Velika casa, 16-18 C",
          "Bin 389 (Baby Grange): Cabernet struktura + Shiraz meso. Ozbiljan NS pairing.",
          "Bin 389 (Baby Grange): Cabernet structure plus Shiraz flesh. A serious New World pairing."),
        W("wine-ridge-lytton-springs", "Ridge Lytton Springs", "red-full", "California, SAD", 14.5, 4, 2,
          ["tamno-voce", "zacini", "orasasti"], 8.5, (45, 70), v, "Velika casa, 16-18 C",
          "Ridge Lytton: Zinfandel field blend; bobicasto voce i zacini. Referenca uz maduro.",
          "Ridge Lytton: Zinfandel field blend; berry fruit and spice. A benchmark with maduro."),
        W("wine-seghesio-zin", "Seghesio Sonoma Zinfandel", "red-full", "California, SAD", 15, 4, 2,
          ["tamno-voce", "zacini", "papar"], 7.5, (18, 28), viv, "Velika casa, 16-18 C",
          "Seghesio: pristupacni Sonoma Zin; papar i dzem. Laksi CA stil uz cigaru.",
          "Seghesio: approachable Sonoma Zin; pepper and jam. An easier CA style with a cigar."),
        W("wine-don-melchor", "Concha y Toro Don Melchor", "red-full", "Maipo, Cile", 14.5, 5, 1,
          ["tamno-voce", "hrast", "zacini", "cedar"], 8.5, (70, 110), v, "Velika casa, 16-18 C",
          "Don Melchor: vodeci cileanski Cabernet; cedar i crno voce. Icon uz punu cigaru.",
          "Don Melchor: leading Chilean Cabernet; cedar and black fruit. An icon with a full cigar."),
        W("wine-korak-cabernet", "Korak Cabernet Sauvignon", "red-full", "Plesivica, Hrvatska", 13.5, 4, 1,
          ["tamno-voce", "hrast", "zacini"], 7.5, (18, 30), viv, "Velika casa, 16-18 C",
          "Korak: kontinentalni HR Cabernet; struktura i crveno voce. Domaci flagship.",
          "Korak: continental Croatian Cabernet; structure and red fruit. A domestic flagship."),
        W("wine-lynch-bages", "Chateau Lynch-Bages", "red-full", "Bordeaux, Francuska", 13.5, 4, 1,
          ["tamno-voce", "cedar", "hrast", "zacini"], 8.5, (90, 160), v, "Velika casa, 16-18 C",
          "Lynch-Bages (Pauillac): cedar, crni ribiz, grafit. Klasicni Bordeaux uz Habano.",
          "Lynch-Bages (Pauillac): cedar, blackcurrant, graphite. Classic Bordeaux with Habano."),
        W("wine-caymus-cabernet", "Caymus Cabernet Sauvignon", "red-full", "Napa Valley, SAD", 14.5, 5, 2,
          ["tamno-voce", "vanilija", "kakao", "hrast"], 8.0, (60, 95), v, "Velika casa, 16-18 C",
          "Caymus: bogati Napa Cab; vanilija i crno voce. Americki stil uz maduro.",
          "Caymus: rich Napa Cab; vanilla and black fruit. American style with maduro."),
        # Srednje / bijelo
        W("wine-antinori-pepploi", "Antinori Peppoli Chianti Classico", "red-medium", "Toskana, Italija", 13.5, 3, 1,
          ["tamno-voce", "voce", "zacini"], 7.5, (14, 22), viv, "Casa, 15-17 C",
          "Peppoli: pristupacni Chianti Classico; tresnja i zacini. Uz blagu do srednju cigaru.",
          "Peppoli: approachable Chianti Classico; cherry and spice. With a mild-to-medium cigar."),
        W("wine-castello-di-ama-chianti", "Castello di Ama Chianti Classico", "red-medium", "Toskana, Italija", 13.5, 3, 1,
          ["tamno-voce", "cvjetno", "mineralno"], 8.0, (28, 45), v, "Casa, 15-17 C",
          "Castello di Ama: finiji Chianti; cvijet i mineralnost. Elegantniji pairing.",
          "Castello di Ama: finer Chianti; flower and minerality. A more elegant pairing."),
        W("wine-louis-jadot-pinot", "Louis Jadot Bourgogne Pinot Noir", "red-medium", "Burgundija, Francuska", 13, 2, 1,
          ["voce", "zemljano", "cvjetno"], 7.5, (18, 28), viv, "Casa, 14-16 C",
          "Jadot regionalni Pinot: crvena tresnja i zemlja. Samo uz blagu Connecticut cigaru.",
          "Jadot regional Pinot: red cherry and earth. Only with a mild Connecticut cigar."),
        W("wine-benvenuti-pinot", "Benvenuti Pinot Noir", "red-medium", "Istra, Hrvatska", 13, 2, 1,
          ["voce", "cvjetno", "mineralno"], 7.5, (16, 26), viv, "Casa, 14-16 C",
          "Benvenuti: istarski Pinot; svjeze voce i mineralnost. Lagani HR pairing.",
          "Benvenuti: Istrian Pinot; fresh fruit and minerality. A light HR pairing."),
        W("wine-kozlovic-merlot", "Kozlovic Merlot", "red-medium", "Istra, Hrvatska", 13.5, 3, 1,
          ["voce", "tamno-voce", "hrast"], 7.0, (12, 20), hr, "Casa, 15-17 C",
          "Kozlovic Merlot: meko voce i blagi hrast. Svakodnevni istarski crveni.",
          "Kozlovic Merlot: soft fruit and gentle oak. An everyday Istrian red."),
        W("wine-roxanich-merlot", "Roxanich Merlot", "red-medium", "Istra, Hrvatska", 13.5, 3, 1,
          ["tamno-voce", "zemljano", "orasasti"], 7.5, (25, 40), viv, "Casa, 15-17 C",
          "Roxanich: duzi maceration stil; kompleksniji Merlot. Uz srednju cigaru.",
          "Roxanich: longer-maceration style; a more complex Merlot. With a medium cigar."),
        W("wine-krauthaker-frankovka", "Krauthaker Frankovka", "red-medium", "Slavonija, Hrvatska", 13, 3, 1,
          ["voce", "zacini", "papar"], 7.0, (8, 14), hr, "Casa, 15-17 C",
          "Krauthaker Frankovka: papar i crveno voce. Lagani kontinentalni pairing.",
          "Krauthaker Frankovka: pepper and red fruit. A light continental pairing."),
        W("wine-belje-frankovka", "Belje Frankovka", "red-medium", "Baranja, Hrvatska", 12.5, 3, 1,
          ["voce", "zacini"], 6.5, (6, 12), hr, "Casa, 15-17 C",
          "Belje: siroko dostupna frankovka; svjeze voce. Ulazni HR crveni.",
          "Belje: widely available Frankovka; fresh fruit. An entry-level HR red."),
        W("wine-krauthaker-grasevina", "Krauthaker Grasevina", "white-fresh", "Slavonija, Hrvatska", 12.5, 2, 1,
          ["jabuka", "citrus", "mineralno"], 7.5, (8, 14), hr, "Dobro ohladjeno, 6-8 C",
          "Krauthaker: standard HR bijelog; jabuka i citrus. Samo uz najblazu cigaru.",
          "Krauthaker: HR white standard; apple and citrus. Only with the mildest cigar."),
        W("wine-enjingi-grasevina", "Enjingi Grasevina", "white-fresh", "Slavonija, Hrvatska", 12.5, 2, 1,
          ["jabuka", "citrus", "med"], 7.5, (9, 16), hr, "Dobro ohladjeno, 6-8 C",
          "Enjingi: malo bogatija grasevina; med i jabuka. Kontrast uz Connecticut.",
          "Enjingi: a slightly richer Grasevina; honey and apple. Contrast with Connecticut."),
        W("wine-stina-posip", "Stina Posip", "white-rich", "Brac, Hrvatska", 13, 3, 1,
          ["citrus", "mineralno", "orasasti"], 8.0, (14, 24), viv, "Ohladjeno, 8-10 C",
          "Stina Posip: mineralan, mediteranski bijeli. Uz blagu cigaru ili aperitiv.",
          "Stina Posip: mineral Mediterranean white. With a mild cigar or as an aperitif."),
        W("wine-krajancic-posip", "Krajancic Posip", "white-rich", "Korcula, Hrvatska", 13.5, 3, 1,
          ["citrus", "orasasti", "mineralno"], 8.0, (16, 28), viv, "Ohladjeno, 8-10 C",
          "Krajancic: referentni korculanski posip; orasi i citrus. Ozbiljniji bijeli pairing.",
          "Krajancic: benchmark Korcula Posip; nuts and citrus. A more serious white pairing."),
        W("wine-kozlovic-malvazija", "Kozlovic Malvazija", "white-fresh", "Istra, Hrvatska", 13, 2, 1,
          ["voce", "citrus", "cvjetno"], 7.5, (10, 18), hr, "Dobro ohladjeno, 6-8 C",
          "Kozlovic: istarska klasika; breskva i bagrem. Svjezina uz blagu cigaru.",
          "Kozlovic: Istrian classic; peach and acacia. Freshness with a mild cigar."),
        W("wine-matosevic-malvazija", "Matosevic Malvazija", "white-fresh", "Istra, Hrvatska", 13, 2, 1,
          ["voce", "mineralno", "citrus"], 7.5, (12, 20), viv, "Dobro ohladjeno, 6-8 C",
          "Matosevic: mineralnija malvazija; citrus i kamen. Elegantan HR bijeli.",
          "Matosevic: a more mineral Malvasia; citrus and stone. An elegant HR white."),
        W("wine-korak-chardonnay", "Korak Chardonnay", "white-rich", "Plesivica, Hrvatska", 13.5, 3, 1,
          ["orasasti", "vanilija", "citrus"], 7.5, (16, 28), viv, "Ohladjeno, 10-12 C",
          "Korak barrique Chardonnay: maslac i citrus. Bogatiji bijeli uz Connecticut.",
          "Korak barrel Chardonnay: butter and citrus. A richer white with Connecticut."),
        W("wine-louis-latour-chardonnay", "Louis Latour Pouilly-Fuisse", "white-rich", "Burgundija, Francuska", 13.5, 3, 1,
          ["orasasti", "citrus", "mineralno"], 8.0, (25, 40), viv, "Ohladjeno, 10-12 C",
          "Latour Pouilly-Fuisse: klasicni bijeli Burgundac; orasi i mineralnost.",
          "Latour Pouilly-Fuisse: classic white Burgundy; nuts and minerality."),
        W("wine-dr-loosen-kabinett", "Dr. Loosen Riesling Kabinett", "white-fresh", "Mosel, Njemacka", 8.5, 2, 3,
          ["citrus", "jabuka", "mineralno", "med"], 8.0, (12, 20), viv, "Dobro ohladjeno, 6-8 C",
          "Dr. Loosen Kabinett: limeta, jabuka, skriljevac, njezna slatkoca. Uz najblazu cigaru.",
          "Dr. Loosen Kabinett: lime, apple, slate, gentle sweetness. With the mildest cigar."),
        W("wine-jj-prum-kabinett", "J.J. Prum Riesling Kabinett", "white-fresh", "Mosel, Njemacka", 9, 2, 3,
          ["citrus", "mineralno", "cvjetno", "med"], 8.5, (22, 35), v, "Dobro ohladjeno, 6-8 C",
          "J.J. Prum: ikona Mosela; precizan, cvjetan, mineralan. Rijedak bijeli uz cigaru.",
          "J.J. Prum: a Mosel icon; precise, floral, mineral. A rare white with a cigar."),
        # Pjenusavo
        W("wine-moet-brut-imperial", "Moet & Chandon Brut Imperial", "sparkling", "Champagne, Francuska", 12, 2, 1,
          ["citrus", "kremasto", "orasasti"], 7.5, (40, 55), "Siroka dostupnost", "Dobro ohladjeno, 6-8 C",
          "Moet Brut Imperial: brioche i citrus; siroko dostupan. Tradicija uz blagu dnevnu cigaru.",
          "Moet Brut Imperial: brioche and citrus; widely available. Tradition with a mild daytime cigar."),
        W("wine-veuve-clicquot-yellow", "Veuve Clicquot Yellow Label Brut", "sparkling", "Champagne, Francuska", 12, 2, 1,
          ["citrus", "kremasto", "voce"], 8.0, (45, 60), "Siroka dostupnost", "Dobro ohladjeno, 6-8 C",
          "Veuve Yellow Label: malo puniji brut; voce i tost. Kontrast uz Connecticut.",
          "Veuve Yellow Label: a slightly fuller brut; fruit and toast. Contrast with Connecticut."),
        W("wine-bollinger-special-cuvee", "Bollinger Special Cuvee", "sparkling", "Champagne, Francuska", 12, 3, 1,
          ["orasasti", "kremasto", "citrus", "hrast"], 8.5, (55, 75), viv, "Dobro ohladjeno, 6-8 C",
          "Bollinger: pinot-tezi, orasasti Champagne. Ozbiljniji pjenusac uz blagu do srednju cigaru.",
          "Bollinger: Pinot-led, nutty Champagne. A more serious sparkler with a mild-to-medium cigar."),
        W("wine-pol-roger-brut", "Pol Roger Brut Reserve", "sparkling", "Champagne, Francuska", 12, 2, 1,
          ["citrus", "kremasto", "mineralno"], 8.5, (50, 70), viv, "Dobro ohladjeno, 6-8 C",
          "Pol Roger: elegantan, fin mousse; citrus i biskvit. Churchillova kuca uz blagu cigaru.",
          "Pol Roger: elegant, fine mousse; citrus and biscuit. Churchill's house with a mild cigar."),
        W("wine-taittinger-brut", "Taittinger Brut Reserve", "sparkling", "Champagne, Francuska", 12, 2, 1,
          ["cvjetno", "citrus", "kremasto"], 8.0, (45, 60), viv, "Dobro ohladjeno, 6-8 C",
          "Taittinger: chardonnay-tezi, cvjetni Champagne. Elegantan uz blagu cigaru.",
          "Taittinger: Chardonnay-led, floral Champagne. Elegant with a mild cigar."),
        W("wine-valdo-prosecco-docg", "Valdo Valdobbiadene Prosecco Superiore DOCG", "sparkling", "Veneto, Italija", 11, 1, 2,
          ["voce", "cvjetno", "citrus"], 7.0, (10, 16), hr, "Dobro ohladjeno, 6-8 C",
          "Valdo DOCG: jabuka i cvijet; lagani prosecco. Samo uz najblazu cigaru.",
          "Valdo DOCG: apple and flower; light Prosecco. Only with the mildest cigar."),
        W("wine-villa-sandi-prosecco", "Villa Sandi Valdobbiadene Prosecco Superiore", "sparkling", "Veneto, Italija", 11, 1, 2,
          ["voce", "citrus", "cvjetno"], 7.5, (12, 18), viv, "Dobro ohladjeno, 6-8 C",
          "Villa Sandi: cist DOCG stil; kruska i citrus. Aperitiv uz Connecticut.",
          "Villa Sandi: clean DOCG style; pear and citrus. Aperitif with Connecticut."),
        W("wine-villa-sandi-cartizze", "Villa Sandi Cartizze", "sparkling", "Veneto, Italija", 11.5, 2, 2,
          ["voce", "kremasto", "cvjetno"], 8.5, (28, 40), viv, "Dobro ohladjeno, 6-8 C",
          "Villa Sandi Cartizze: vrh prosecco piramide; kremast, cvjetan. Ozbiljniji mousse uz blagu cigaru.",
          "Villa Sandi Cartizze: top of the Prosecco pyramid; creamy, floral. A more serious mousse with a mild cigar."),
        W("wine-bisol-cartizze", "Bisol Cartizze", "sparkling", "Veneto, Italija", 11.5, 2, 2,
          ["voce", "med", "cvjetno"], 8.5, (30, 45), v, "Dobro ohladjeno, 6-8 C",
          "Bisol Cartizze: referentni Cartizze; med i bijelo cvijece. Premium prosecco pairing.",
          "Bisol Cartizze: benchmark Cartizze; honey and white flowers. A premium Prosecco pairing."),
        W("wine-bisol-crede", "Bisol Crede Valdobbiadene DOCG", "sparkling", "Veneto, Italija", 11.5, 1, 2,
          ["voce", "citrus", "mineralno"], 8.0, (14, 22), viv, "Dobro ohladjeno, 6-8 C",
          "Bisol Crede: susi, mineralniji prosecco. Bolji omjer cijene i ozbiljnosti.",
          "Bisol Crede: a drier, more mineral Prosecco. Better value-to-seriousness ratio."),
        W("wine-juve-y-camps-reserva", "Juve y Camps Reserva de la Familia Brut Nature", "sparkling", "Penedes, Spanjolska", 12, 2, 1,
          ["orasasti", "citrus", "kremasto"], 7.5, (12, 20), viv, "Dobro ohladjeno, 6-8 C",
          "Juve y Camps Brut Nature: bez dozaze; orasi i citrus. Cava vrijednost uz blagu cigaru.",
          "Juve y Camps Brut Nature: no dosage; nuts and citrus. Cava value with a mild cigar."),
        W("wine-gramona-imperial", "Gramona Imperial Brut", "sparkling", "Penedes, Spanjolska", 12, 2, 1,
          ["orasasti", "kremasto", "mineralno"], 8.5, (25, 40), v, "Dobro ohladjeno, 6-8 C",
          "Gramona Imperial: dugo odlezavanje; brioche i orasi. Najbolja Cava kuca uz cigaru.",
          "Gramona Imperial: long ageing; brioche and nuts. The best Cava house with a cigar."),
        W("wine-tomac-klasik", "Tomac Klasik", "sparkling", "Plesivica, Hrvatska", 12, 2, 1,
          ["citrus", "mineralno", "kremasto"], 8.0, (18, 28), viv, "Dobro ohladjeno, 6-8 C",
          "Tomac Klasik: plesivicka klasicna metoda; citrus i kvasac. HR referentni pjenusac.",
          "Tomac Klasik: Plesivica classic method; citrus and yeast. Benchmark Croatian sparkling."),
        W("wine-tomac-amfora", "Tomac Amfora", "sparkling", "Plesivica, Hrvatska", 12, 2, 1,
          ["orasasti", "mineralno", "citrus"], 8.5, (28, 42), viv, "Dobro ohladjeno, 6-8 C",
          "Tomac Amfora: fermentacija u amforama; kompleksniji, orasasti. Svjetska razina uz blagu cigaru.",
          "Tomac Amfora: amphora fermentation; more complex, nutty. World-class with a mild cigar."),
        W("wine-misal-brut", "Misal Persuric Brut", "sparkling", "Istra, Hrvatska", 12, 2, 1,
          ["citrus", "voce", "mineralno"], 7.5, (15, 24), viv, "Dobro ohladjeno, 6-8 C",
          "Misal Brut: prvi HR klasicni metoda (Visnjan); svjez citrus. Ulaz u HR pjenusce.",
          "Misal Brut: first Croatian classic method (Visnjan); fresh citrus. Entry to HR sparkling."),
        W("wine-misal-prestige", "Misal Persuric Prestige", "sparkling", "Istra, Hrvatska", 12, 2, 1,
          ["kremasto", "orasasti", "citrus"], 8.0, (25, 38), viv, "Dobro ohladjeno, 6-8 C",
          "Misal Prestige: duze na kvascima; kremastiji. Bolji HR pairing uz Connecticut.",
          "Misal Prestige: longer on lees; creamier. A better HR pairing with Connecticut."),
        W("wine-sember-brut", "Sember Brut", "sparkling", "Plesivica, Hrvatska", 12, 2, 1,
          ["citrus", "mineralno", "cvjetno"], 8.0, (16, 26), viv, "Dobro ohladjeno, 6-8 C",
          "Sember: jos jedan plesivicki klasik; precizan i mineralan. Alternativa Tomacu.",
          "Sember: another Plesivica classic; precise and mineral. An alternative to Tomac."),
        W("wine-berlucchi-61", "Berlucchi 61 Franciacorta Brut", "sparkling", "Lombardija, Italija", 12.5, 2, 1,
          ["citrus", "kremasto", "orasasti"], 8.0, (22, 32), viv, "Dobro ohladjeno, 6-8 C",
          "Berlucchi 61: pionir Franciacorte; citrus i brioche. Alternativa Ca' del Boscu.",
          "Berlucchi 61: Franciacorta pioneer; citrus and brioche. An alternative to Ca' del Bosco."),
    ]


def build(old: list[dict]) -> list[dict]:
    by_id = {w["id"]: w for w in old}
    out: list[dict] = []
    for wid in sorted(KEEP_IDS):
        if wid not in by_id:
            raise SystemExit(f"Missing keep id: {wid}")
        w = deepcopy(by_id[wid])
        if wid in RENAMES:
            w["name"] = RENAMES[wid]
        for lang in ("hr", "en"):
            if isinstance(w.get("notes"), dict) and lang in w["notes"]:
                w["notes"][lang] = (
                    w["notes"][lang].replace("\u2014", ",").replace("—", ",")
                )
        out.append(w)
    out.extend(new_entries())
    ids = [w["id"] for w in out]
    if len(ids) != len(set(ids)):
        from collections import Counter
        dup = [i for i, c in Counter(ids).items() if c > 1]
        raise SystemExit(f"Duplicate ids: {dup}")
    style_order = [
        "port-tawny", "port-ruby", "sherry-dry", "sherry-sweet", "madeira", "prosek",
        "dessert-wine", "red-full", "red-medium", "white-rich", "white-fresh", "sparkling",
    ]
    rank = {s: i for i, s in enumerate(style_order)}
    out.sort(key=lambda w: (rank.get(w["style"], 99), w["name"].lower()))
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    old = json.loads(WINES_PATH.read_text(encoding="utf-8"))
    new = build(old)
    from collections import Counter
    print(f"old={len(old)} new={len(new)} kept={len(KEEP_IDS)} added={len(new)-len(KEEP_IDS)}")
    for s, c in Counter(w["style"] for w in new).most_common():
        print(f"  {c:3d}  {s}")
    if args.dry_run:
        return
    WINES_PATH.write_text(json.dumps(new, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    print(f"Wrote {WINES_PATH}")


if __name__ == "__main__":
    main()
